/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 car.glb --transform 
Files: car.glb [26.94MB] > C:\Users\ayoub\Desktop\Code\namx-huv\public\car-transformed.glb [2.39MB] (91%)
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-concept-car-006-public-domain-cc0-a4e19bb6e6394c4a95d4319ef7d265ba
Title: FREE Concept Car 006 - public domain (CC0)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/car-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="Object_81">
              <primitive object={nodes._rootJoint} />
              <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_84.skeleton} />
              <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_86.skeleton} />
              <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_88.skeleton} />
              <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_90.skeleton} />
              <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_91.skeleton} />
              <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_92.skeleton} />
              <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.PaletteMaterial004} skeleton={nodes.Object_93.skeleton} />
              <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_94.skeleton} />
              <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.pattern_4} skeleton={nodes.Object_95.skeleton} />
              <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_96.skeleton} />
              <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_98.skeleton} />
              <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_99.skeleton} />
              <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_100.skeleton} />
              <skinnedMesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.PaletteMaterial004} skeleton={nodes.Object_101.skeleton} />
              <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_102.skeleton} />
              <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.pattern_4} skeleton={nodes.Object_103.skeleton} />
              <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_104.skeleton} />
              <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_106.skeleton} />
              <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_108.skeleton} />
              <skinnedMesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_110.skeleton} />
              <skinnedMesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.pattern_4} skeleton={nodes.Object_112.skeleton} />
              <skinnedMesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.pattern_4} skeleton={nodes.Object_114.skeleton} />
              <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_116.skeleton} />
              <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.pattern_4} skeleton={nodes.Object_118.skeleton} />
              <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_120.skeleton} />
              <skinnedMesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_121.skeleton} />
              <skinnedMesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_122.skeleton} />
              <skinnedMesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.PaletteMaterial004} skeleton={nodes.Object_123.skeleton} />
              <skinnedMesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_124.skeleton} />
              <skinnedMesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.pattern_4} skeleton={nodes.Object_125.skeleton} />
              <skinnedMesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_126.skeleton} />
              <skinnedMesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_128.skeleton} />
              <skinnedMesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_130.skeleton} />
              <skinnedMesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_132.skeleton} />
              <skinnedMesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_134.skeleton} />
              <skinnedMesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_136.skeleton} />
              <skinnedMesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_138.skeleton} />
              <skinnedMesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_139.skeleton} />
              <skinnedMesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_140.skeleton} />
              <skinnedMesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.PaletteMaterial004} skeleton={nodes.Object_141.skeleton} />
              <skinnedMesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_142.skeleton} />
              <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.pattern_4} skeleton={nodes.Object_143.skeleton} />
              <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_144.skeleton} />
              <skinnedMesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.pattern_4} skeleton={nodes.Object_146.skeleton} />
              <skinnedMesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_148.skeleton} />
              <skinnedMesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_150.skeleton} />
              <skinnedMesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_152.skeleton} />
              <skinnedMesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_154.skeleton} />
              <skinnedMesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_167.skeleton} />
              <skinnedMesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_169.skeleton} />
              <skinnedMesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_171.skeleton} />
              <skinnedMesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_173.skeleton} />
              <skinnedMesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_175.skeleton} />
              <skinnedMesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_177.skeleton} />
              <skinnedMesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_179.skeleton} />
              <skinnedMesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_181.skeleton} />
              <skinnedMesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_183.skeleton} />
              <skinnedMesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_185.skeleton} />
              <skinnedMesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_187.skeleton} />
              <skinnedMesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_189.skeleton} />
              <skinnedMesh name="Object_191" geometry={nodes.Object_191.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_191.skeleton} />
              <skinnedMesh name="Object_193" geometry={nodes.Object_193.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_193.skeleton} />
              <skinnedMesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_194.skeleton} />
              <skinnedMesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_196.skeleton} />
              <skinnedMesh name="Object_197" geometry={nodes.Object_197.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_197.skeleton} />
              <skinnedMesh name="Object_199" geometry={nodes.Object_199.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_199.skeleton} />
              <skinnedMesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_201.skeleton} />
              <skinnedMesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_203.skeleton} />
              <skinnedMesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_204.skeleton} />
              <skinnedMesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_206.skeleton} />
              <skinnedMesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_207.skeleton} />
              <skinnedMesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_209.skeleton} />
              <skinnedMesh name="Object_211" geometry={nodes.Object_211.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_211.skeleton} />
              <skinnedMesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_212.skeleton} />
              <skinnedMesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_214.skeleton} />
              <skinnedMesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_216.skeleton} />
              <skinnedMesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_217.skeleton} />
              <skinnedMesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_219.skeleton} />
              <skinnedMesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_220.skeleton} />
              <skinnedMesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_222.skeleton} />
              <skinnedMesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_224.skeleton} />
              <skinnedMesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_225.skeleton} />
              <skinnedMesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_227.skeleton} />
              <skinnedMesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_229.skeleton} />
              <skinnedMesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_230.skeleton} />
              <skinnedMesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_232.skeleton} />
              <skinnedMesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_233.skeleton} />
              <skinnedMesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_235.skeleton} />
              <skinnedMesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_237.skeleton} />
              <skinnedMesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_238.skeleton} />
              <skinnedMesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_240.skeleton} />
              <skinnedMesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_242.skeleton} />
              <skinnedMesh name="Object_243" geometry={nodes.Object_243.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_243.skeleton} />
              <skinnedMesh name="Object_245" geometry={nodes.Object_245.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_245.skeleton} />
              <skinnedMesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_246.skeleton} />
              <skinnedMesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_248.skeleton} />
              <skinnedMesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_250.skeleton} />
              <skinnedMesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_252.skeleton} />
              <skinnedMesh name="Object_253" geometry={nodes.Object_253.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_253.skeleton} />
              <skinnedMesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_255.skeleton} />
              <skinnedMesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_256.skeleton} />
              <skinnedMesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_258.skeleton} />
              <skinnedMesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_260.skeleton} />
              <skinnedMesh name="Object_261" geometry={nodes.Object_261.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_261.skeleton} />
              <skinnedMesh name="Object_263" geometry={nodes.Object_263.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_263.skeleton} />
              <skinnedMesh name="Object_265" geometry={nodes.Object_265.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_265.skeleton} />
              <skinnedMesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_266.skeleton} />
              <skinnedMesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_268.skeleton} />
              <skinnedMesh name="Object_269" geometry={nodes.Object_269.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_269.skeleton} />
              <skinnedMesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_271.skeleton} />
              <skinnedMesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_273.skeleton} />
              <skinnedMesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_274.skeleton} />
              <skinnedMesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_276.skeleton} />
              <skinnedMesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_278.skeleton} />
              <skinnedMesh name="Object_279" geometry={nodes.Object_279.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_279.skeleton} />
              <skinnedMesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_281.skeleton} />
              <skinnedMesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_282.skeleton} />
              <skinnedMesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_284.skeleton} />
              <skinnedMesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_286.skeleton} />
              <skinnedMesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_287.skeleton} />
              <skinnedMesh name="Object_289" geometry={nodes.Object_289.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_289.skeleton} />
              <skinnedMesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_291.skeleton} />
              <skinnedMesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_293.skeleton} />
              <skinnedMesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_295.skeleton} />
              <skinnedMesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_297.skeleton} />
              <skinnedMesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_299.skeleton} />
              <skinnedMesh name="Object_301" geometry={nodes.Object_301.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_301.skeleton} />
              <skinnedMesh name="Object_303" geometry={nodes.Object_303.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_303.skeleton} />
              <skinnedMesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_305.skeleton} />
              <skinnedMesh name="Object_307" geometry={nodes.Object_307.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_307.skeleton} />
              <skinnedMesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_308.skeleton} />
              <skinnedMesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_310.skeleton} />
              <skinnedMesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_311.skeleton} />
              <skinnedMesh name="Object_313" geometry={nodes.Object_313.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_313.skeleton} />
              <skinnedMesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_314.skeleton} />
              <skinnedMesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_316.skeleton} />
              <skinnedMesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_317.skeleton} />
              <skinnedMesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_319.skeleton} />
              <skinnedMesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_321.skeleton} />
              <skinnedMesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_323.skeleton} />
              <skinnedMesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_325.skeleton} />
              <skinnedMesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_326.skeleton} />
              <skinnedMesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_328.skeleton} />
              <skinnedMesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_330.skeleton} />
              <skinnedMesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_331.skeleton} />
              <skinnedMesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_333.skeleton} />
              <skinnedMesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_334.skeleton} />
              <skinnedMesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_336.skeleton} />
              <skinnedMesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_337.skeleton} />
              <skinnedMesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_339.skeleton} />
              <skinnedMesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_340.skeleton} />
              <skinnedMesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_342.skeleton} />
              <skinnedMesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_344.skeleton} />
              <skinnedMesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_346.skeleton} />
              <skinnedMesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_347.skeleton} />
              <skinnedMesh name="Object_349" geometry={nodes.Object_349.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_349.skeleton} />
              <skinnedMesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_351.skeleton} />
              <skinnedMesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_352.skeleton} />
              <skinnedMesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_354.skeleton} />
              <skinnedMesh name="Object_355" geometry={nodes.Object_355.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_355.skeleton} />
              <skinnedMesh name="Object_357" geometry={nodes.Object_357.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_357.skeleton} />
              <skinnedMesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_358.skeleton} />
              <skinnedMesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_360.skeleton} />
              <skinnedMesh name="Object_361" geometry={nodes.Object_361.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_361.skeleton} />
              <skinnedMesh name="Object_363" geometry={nodes.Object_363.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_363.skeleton} />
              <skinnedMesh name="Object_365" geometry={nodes.Object_365.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_365.skeleton} />
              <skinnedMesh name="Object_367" geometry={nodes.Object_367.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_367.skeleton} />
              <skinnedMesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_368.skeleton} />
              <skinnedMesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_370.skeleton} />
              <skinnedMesh name="Object_371" geometry={nodes.Object_371.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_371.skeleton} />
              <skinnedMesh name="Object_373" geometry={nodes.Object_373.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_373.skeleton} />
              <skinnedMesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_374.skeleton} />
              <skinnedMesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_376.skeleton} />
              <skinnedMesh name="Object_377" geometry={nodes.Object_377.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_377.skeleton} />
              <skinnedMesh name="Object_379" geometry={nodes.Object_379.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_379.skeleton} />
              <skinnedMesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_380.skeleton} />
              <skinnedMesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_382.skeleton} />
              <skinnedMesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_384.skeleton} />
              <skinnedMesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_386.skeleton} />
              <skinnedMesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_388.skeleton} />
              <skinnedMesh name="Object_389" geometry={nodes.Object_389.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_389.skeleton} />
              <skinnedMesh name="Object_391" geometry={nodes.Object_391.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_391.skeleton} />
              <skinnedMesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_392.skeleton} />
              <skinnedMesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_394.skeleton} />
              <skinnedMesh name="Object_395" geometry={nodes.Object_395.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_395.skeleton} />
              <skinnedMesh name="Object_397" geometry={nodes.Object_397.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_397.skeleton} />
              <skinnedMesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_398.skeleton} />
              <skinnedMesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_400.skeleton} />
              <skinnedMesh name="Object_401" geometry={nodes.Object_401.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_401.skeleton} />
              <skinnedMesh name="Object_403" geometry={nodes.Object_403.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_403.skeleton} />
              <skinnedMesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_404.skeleton} />
              <skinnedMesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_406.skeleton} />
              <skinnedMesh name="Object_407" geometry={nodes.Object_407.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_407.skeleton} />
              <skinnedMesh name="Object_409" geometry={nodes.Object_409.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_409.skeleton} />
              <skinnedMesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_410.skeleton} />
              <skinnedMesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_412.skeleton} />
              <skinnedMesh name="Object_413" geometry={nodes.Object_413.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_413.skeleton} />
              <skinnedMesh name="Object_415" geometry={nodes.Object_415.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_415.skeleton} />
              <skinnedMesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_416.skeleton} />
              <skinnedMesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_418.skeleton} />
              <skinnedMesh name="Object_419" geometry={nodes.Object_419.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_419.skeleton} />
              <skinnedMesh name="Object_421" geometry={nodes.Object_421.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_421.skeleton} />
              <skinnedMesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_422.skeleton} />
              <skinnedMesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_424.skeleton} />
              <skinnedMesh name="Object_425" geometry={nodes.Object_425.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_425.skeleton} />
              <skinnedMesh name="Object_427" geometry={nodes.Object_427.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_427.skeleton} />
              <skinnedMesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_428.skeleton} />
              <skinnedMesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_430.skeleton} />
              <skinnedMesh name="Object_431" geometry={nodes.Object_431.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_431.skeleton} />
              <skinnedMesh name="Object_433" geometry={nodes.Object_433.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_433.skeleton} />
              <skinnedMesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_434.skeleton} />
              <skinnedMesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_436.skeleton} />
              <skinnedMesh name="Object_437" geometry={nodes.Object_437.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_437.skeleton} />
              <skinnedMesh name="Object_439" geometry={nodes.Object_439.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_439.skeleton} />
              <skinnedMesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_440.skeleton} />
              <skinnedMesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_442.skeleton} />
              <skinnedMesh name="Object_443" geometry={nodes.Object_443.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_443.skeleton} />
              <skinnedMesh name="Object_445" geometry={nodes.Object_445.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_445.skeleton} />
              <skinnedMesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_446.skeleton} />
              <skinnedMesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_448.skeleton} />
              <skinnedMesh name="Object_449" geometry={nodes.Object_449.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_449.skeleton} />
              <skinnedMesh name="Object_451" geometry={nodes.Object_451.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_451.skeleton} />
              <skinnedMesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_452.skeleton} />
              <skinnedMesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_454.skeleton} />
              <skinnedMesh name="Object_455" geometry={nodes.Object_455.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_455.skeleton} />
              <skinnedMesh name="Object_457" geometry={nodes.Object_457.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_457.skeleton} />
              <skinnedMesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_458.skeleton} />
              <skinnedMesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_460.skeleton} />
              <skinnedMesh name="Object_461" geometry={nodes.Object_461.geometry} material={materials.bolt_metal_threads} skeleton={nodes.Object_461.skeleton} />
              <skinnedMesh name="Object_463" geometry={nodes.Object_463.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_463.skeleton} />
              <skinnedMesh name="Object_465" geometry={nodes.Object_465.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_465.skeleton} />
              <skinnedMesh name="Object_467" geometry={nodes.Object_467.geometry} material={materials.PaletteMaterial003} skeleton={nodes.Object_467.skeleton} />
              <skinnedMesh name="Object_469" geometry={nodes.Object_469.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_469.skeleton} />
              <skinnedMesh name="Object_471" geometry={nodes.Object_471.geometry} material={materials.PaletteMaterial005} skeleton={nodes.Object_471.skeleton} />
              <skinnedMesh name="Object_473" geometry={nodes.Object_473.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_473.skeleton} />
              <skinnedMesh name="Object_475" geometry={nodes.Object_475.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_475.skeleton} />
              <skinnedMesh name="Object_477" geometry={nodes.Object_477.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_477.skeleton} />
              <skinnedMesh name="Object_479" geometry={nodes.Object_479.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_479.skeleton} />
              <skinnedMesh name="Object_481" geometry={nodes.Object_481.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_481.skeleton} />
              <skinnedMesh name="Object_483" geometry={nodes.Object_483.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_483.skeleton} />
              <skinnedMesh name="Object_485" geometry={nodes.Object_485.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_485.skeleton} />
              <skinnedMesh name="Object_487" geometry={nodes.Object_487.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_487.skeleton} />
              <skinnedMesh name="Object_489" geometry={nodes.Object_489.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_489.skeleton} />
              <skinnedMesh name="Object_491" geometry={nodes.Object_491.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_491.skeleton} />
              <skinnedMesh name="Object_493" geometry={nodes.Object_493.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_493.skeleton} />
              <skinnedMesh name="Object_495" geometry={nodes.Object_495.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_495.skeleton} />
              <skinnedMesh name="Object_497" geometry={nodes.Object_497.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_497.skeleton} />
              <skinnedMesh name="Object_499" geometry={nodes.Object_499.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_499.skeleton} />
              <skinnedMesh name="Object_501" geometry={nodes.Object_501.geometry} material={materials.PaletteMaterial006} skeleton={nodes.Object_501.skeleton} />
              <skinnedMesh name="Object_503" geometry={nodes.Object_503.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_503.skeleton} />
              <skinnedMesh name="Object_505" geometry={nodes.Object_505.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_505.skeleton} />
              <skinnedMesh name="Object_507" geometry={nodes.Object_507.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_507.skeleton} />
            </group>
          </group>
        </group>
        <mesh name="Plane051_shadow_0" geometry={nodes.Plane051_shadow_0.geometry} material={materials.shadow} position={[0, 0, -2.42]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.603, 3.83, 3.83]} />
        <mesh name="Cube020_body_0" geometry={nodes.Cube020_body_0.geometry} material={materials.PaletteMaterial001} position={[0, 0, -2.182]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Cube027_plasticMatte_0" geometry={nodes.Cube027_plasticMatte_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -2.182]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Cube165_headlightCovers_0" geometry={nodes.Cube165_headlightCovers_0.geometry} material={materials.PaletteMaterial003} position={[0, 0, -2.182]} rotation={[-Math.PI / 2, 0, 0]} scale={1.141} />
        <mesh name="Cube169_grill_0" geometry={nodes.Cube169_grill_0.geometry} material={materials.grill} position={[0, 0, -2.182]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Torus006_pattern_4_0" geometry={nodes.Torus006_pattern_4_0.geometry} material={materials.pattern_4} position={[0.387, 1.125, -2.012]} rotation={[-1.222, 0, 0]} />
        <mesh name="SW_base_blocker_0" geometry={nodes.SW_base_blocker_0.geometry} material={materials.PaletteMaterial005} position={[0.387, 1.125, -2.012]} rotation={[-1.222, 0, 0]} />
        <mesh name="Text024_light001_0" geometry={nodes.Text024_light001_0.geometry} material={materials.PaletteMaterial004} position={[0.286, 1.226, -1.788]} rotation={[-2.793, 0, -Math.PI]} scale={0.907} />
        <mesh name="bolt_12019_bolt_metal_threads_0" geometry={nodes.bolt_12019_bolt_metal_threads_0.geometry} material={materials.bolt_metal_threads} position={[0.994, 0.931, -1.56]} rotation={[-1.834, -0.084, -0.284]} />
        <mesh name="wheel_701_wheel_nitto_0" geometry={nodes.wheel_701_wheel_nitto_0.geometry} material={materials.wheel_nitto} position={[1.1, 0.467, -1.099]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Cube023_glass_0" geometry={nodes.Cube023_glass_0.geometry} material={materials.PaletteMaterial006} position={[0, 0, -2.182]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
